[build]
builder = "nixpacks"
buildCommand = "bun install"

[deploy]
startCommand = "bun run start"
restartPolicyType = "always"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/health"
port = 3000
timeout = 30
maxRetries = 3 